// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"

	time "time"
)

// AuthRepository is an autogenerated mock type for the AuthRepository type
type AuthRepository struct {
	mock.Mock
}

// DeleteAccessToken provides a mock function with given fields: ctx, userID
func (_m *AuthRepository) DeleteAccessToken(ctx context.Context, userID uint) error {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAccessToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, userID)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// SetAccessToken provides a mock function with given fields: ctx, userID, accessToken, expiry
func (_m *AuthRepository) SetAccessToken(ctx context.Context, userID uint, accessToken string, expiry time.Duration) error {
	ret := _m.Called(ctx, userID, accessToken, expiry)

	if len(ret) == 0 {
		panic("no return value specified for SetAccessToken")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string, time.Duration) error); ok {
		r0 = rf(ctx, userID, accessToken, expiry)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// ValidateAccessToken provides a mock function with given fields: ctx, userID, accessToken
func (_m *AuthRepository) ValidateAccessToken(ctx context.Context, userID uint, accessToken string) (bool, error) {
	ret := _m.Called(ctx, userID, accessToken)

	if len(ret) == 0 {
		panic("no return value specified for ValidateAccessToken")
	}

	var r0 bool
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint, string) (bool, error)); ok {
		return rf(ctx, userID, accessToken)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint, string) bool); ok {
		r0 = rf(ctx, userID, accessToken)
	} else {
		r0 = ret.Get(0).(bool)
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint, string) error); ok {
		r1 = rf(ctx, userID, accessToken)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewAuthRepository creates a new instance of AuthRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAuthRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *AuthRepository {
	mock := &AuthRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
