// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"

	entity "wtm-backend/internal/domain/entity"

	jwt "wtm-backend/pkg/jwt"

	mock "github.com/stretchr/testify/mock"
)

// Middleware is an autogenerated mock type for the Middleware type
type Middleware struct {
	mock.Mock
}

// GenerateUserFromClaimToken provides a mock function with given fields: claim
func (_m *Middleware) GenerateUserFromClaimToken(claim *jwt.JwtClaims) *entity.User {
	ret := _m.Called(claim)

	if len(ret) == 0 {
		panic("no return value specified for GenerateUserFromClaimToken")
	}

	var r0 *entity.User
	if rf, ok := ret.Get(0).(func(*jwt.JwtClaims) *entity.User); ok {
		r0 = rf(claim)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	return r0
}

// GenerateUserFromContext provides a mock function with given fields: ctx
func (_m *Middleware) GenerateUserFromContext(ctx context.Context) (*entity.User, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GenerateUserFromContext")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (*entity.User, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) *entity.User); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewMiddleware creates a new instance of Middleware. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMiddleware(t interface {
	mock.TestingT
	Cleanup(func())
}) *Middleware {
	mock := &Middleware{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
