// Code generated by mockery v2.53.4. DO NOT EDIT.

package mocks

import (
	context "context"
	"wtm-backend/internal/repository/filter"

	entity "wtm-backend/internal/domain/entity"

	mock "github.com/stretchr/testify/mock"
)

// UserRepository is an autogenerated mock type for the UserRepository type
type UserRepository struct {
	mock.Mock
}

func (_m *UserRepository) GetAgentCompanies(ctx context.Context, search string, limit, page int) ([]entity.AgentCompany, int64, error) {
	//TODO implement me
	panic("implement me")
}

func (_m *UserRepository) GetUsersByAgentCompany(ctx context.Context, agentCompanyID uint, search string, limit, page int) ([]entity.User, int64, error) {
	//TODO implement me
	panic("implement me")
}

func (_m *UserRepository) GetUserByRole(ctx context.Context, roleID uint, search string, limit, page int) ([]entity.User, int64, error) {
	//TODO implement me
	panic("implement me")
}

func (_m *UserRepository) GetUsers(ctx context.Context, filter filter.UserFilter) ([]entity.User, int64, error) {
	//TODO implement me
	panic("implement me")
}

func (_m *UserRepository) BulkUpdatePromoGroupMember(ctx context.Context, memberIDs []uint, promoGroupID uint) error {
	//TODO implement me
	panic("implement me")
}

func (_m *UserRepository) GetAllRolesWithPermissions(ctx context.Context) ([]entity.Role, error) {
	//TODO implement me
	panic("implement me")
}

func (_m *UserRepository) GetAllPermissions(ctx context.Context) ([]entity.Permission, error) {
	//TODO implement me
	panic("implement me")
}

func (_m *UserRepository) GetPermissionByPageAction(ctx context.Context, page, action string) (*entity.Permission, error) {
	//TODO implement me
	panic("implement me")
}

func (_m *UserRepository) AddRolePermission(ctx context.Context, roleID, permissionID uint) error {
	//TODO implement me
	panic("implement me")
}

func (_m *UserRepository) RemoveRolePermission(ctx context.Context, roleID, permissionID uint) error {
	//TODO implement me
	panic("implement me")
}

func (_m *UserRepository) HasRolePermission(ctx context.Context, roleID, permissionID uint) (bool, error) {
	//TODO implement me
	panic("implement me")
}

func (_m *UserRepository) GetStatusUsers(ctx context.Context, filter *filter.DefaultFilter) ([]entity.StatusUser, int64, error) {
	//TODO implement me
	panic("implement me")
}

func (_m *UserRepository) UpdateStatusUser(ctx context.Context, id uint, status uint) (*entity.User, error) {
	//TODO implement me
	panic("implement me")
}

// CreateAgentCompany provides a mock function with given fields: ctx, agentCompany
func (_m *UserRepository) CreateAgentCompany(ctx context.Context, agentCompany string) (*entity.AgentCompany, error) {
	ret := _m.Called(ctx, agentCompany)

	if len(ret) == 0 {
		panic("no return value specified for CreateAgentCompany")
	}

	var r0 *entity.AgentCompany
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.AgentCompany, error)); ok {
		return rf(ctx, agentCompany)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.AgentCompany); ok {
		r0 = rf(ctx, agentCompany)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.AgentCompany)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, agentCompany)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateUser provides a mock function with given fields: ctx, user
func (_m *UserRepository) CreateUser(ctx context.Context, user *entity.User) (*entity.User, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for CreateUser")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.User) (*entity.User, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.User) *entity.User); ok {
		r0 = rf(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByID provides a mock function with given fields: ctx, userID
func (_m *UserRepository) GetUserByID(ctx context.Context, userID uint) (*entity.User, error) {
	ret := _m.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) (*entity.User, error)); ok {
		return rf(ctx, userID)
	}
	if rf, ok := ret.Get(0).(func(context.Context, uint) *entity.User); ok {
		r0 = rf(ctx, userID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, uint) error); ok {
		r1 = rf(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUserByUsername provides a mock function with given fields: ctx, username
func (_m *UserRepository) GetUserByUsername(ctx context.Context, username string) (*entity.User, error) {
	ret := _m.Called(ctx, username)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByUsername")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*entity.User, error)); ok {
		return rf(ctx, username)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *entity.User); ok {
		r0 = rf(ctx, username)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, username)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateUser provides a mock function with given fields: ctx, user
func (_m *UserRepository) UpdateUser(ctx context.Context, user *entity.User) (*entity.User, error) {
	ret := _m.Called(ctx, user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 *entity.User
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, *entity.User) (*entity.User, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, *entity.User) *entity.User); ok {
		r0 = rf(ctx, user)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*entity.User)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, *entity.User) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// WithTransaction provides a mock function with given fields: ctx, fn
func (_m *UserRepository) WithTransaction(ctx context.Context, fn func(context.Context) error) error {
	ret := _m.Called(ctx, fn)

	if len(ret) == 0 {
		panic("no return value specified for WithTransaction")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, func(context.Context) error) error); ok {
		r0 = rf(ctx, fn)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewUserRepository creates a new instance of UserRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserRepository {
	mock := &UserRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
